substitutions:
  _APP: 'triggers'
  _DIR: 'project/build-triggers'
  _TF_ACTION: 'apply -auto-approve'

steps:
 # 0. Initialise Terraform environment
-  id: terraform-init
   name: hashicorp/terraform:0.13.5
   dir: '${_DIR}'   
   args: ['init']

 # 1. Apply tf plan using hashicorp docker image 
- id: 'tf plan/apply'
  name: hashicorp/terraform:0.13.5
  #  name: 'gcr.io/bi-builds-prd/terragrunt'
  dir: '${_DIR}'
  args:
  - '${_TF_ACTION}'
  env:
  ####- 'PULL_REQUEST_ID=$_PR_NUMBER
  - 'BRANCH=$BRANCH_NAME'

options:
    substitution_option: 'ALLOW_LOOSE'
timeout: 1200s
tags: ['cubicbi-${_APP}-${_TF_ACTION}']
