steps:
 # 0. Initialise Terraform environment
-  name: hashicorp/terraform:0.13.5
   id: terraform-init
   args: ['init']
   dir: 'infra/'

#  # 1. Select Target Workspace
# -  name: hashicorp/terraform:0.13.5
#    id: terraform-workspace
#    args: ['workspace', 'select', '${_ENV}']
#    dir: 'infra/'

 # 2. Plan Terraform
-  name: hashicorp/terraform:0.13.5
   id: terraform-plan
   args: ['${_TF_ACTION}']
   dir: 'infra/'
