# # Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# provider "google" {
#     # credentials = "terraform-test-gkey.json"
#     # project     = "terraform-test-296812"
#     credentials = "C:\\Users\\neil\\OneDrive - Cubic BI Ltd\\GoogleCloudPlatform\\GoogleCloudKeys\\cubicbi-dev01-20201201.json"
#     # New-Item env:GOOGLE_APPLICATION_CREDENTIALS -value "C:\Users\neil\OneDrive - Cubic BI Ltd\GoogleCloudPlatform\GoogleCloudKeys\cubicbi-dev01-20201201.json"    
#     project     = local.project.name
#     region      = local.project.region
# }
