substitutions:
# cloud run image vars
  _DIR: cloudrun
  _CR_NAME: 'cr-test-cloud-run'
  _PORT: '8080'
# terraform apply vars
  #_DIR: 'application_modules/file_transfer/cf_file_transfer'  
  _APP: 'cr-test-cloud-run'
  _PACKAGES_DIR: 'code/packages'
  _TF_ACTION: 'apply'

steps:
- id: 'build-cr-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  dir: $_DIR
  env:
  - 'PORT=${_PORT}'
  - 'CR_NAME=${_CR_NAME}'
  args:
  - 'build'
  - '--build-arg'
  - CR_NAME=${_CR_NAME}    
  - '--build-arg'
  - PORT=${_PORT}
  - '--tag'
  - 'gcr.io/${PROJECT_ID}/cloudrun:${_CR_NAME}'
  - '--tag'
  - 'gcr.io/${PROJECT_ID}/cloudrun:latest'
- '.'

- id: 'tf plan/apply'
  name: 'gcr.io/cubicbi-dev/terragrunt'
  dir: '${_DIR}'
  args:
  - '${_TF_ACTION}'
  env:
  - 'PULL_REQUEST_ID=$_PR_NUMBER'
  - 'BRANCH=$BRANCH_NAME'

options:
    substitution_option: 'ALLOW_LOOSE'

tags:  ['barb-service-step-cloudrun']
