substitutions:
  _DIR: 'project/project-meta'
  _APP: 'project-meta'
  _TF_ACTION: 'apply'
steps:
- id: 'tf plan/apply'
  name: 'gcr.io/cubicbi-dev/terragrunt'
  dir: '$_DIR'
  args:
  - '${_TF_ACTION}'
  env:
  - 'PULL_REQUEST_ID=$_PR_NUMBER'
  - 'BRANCH=$BRANCH_NAME'

options:
  substitution_option: 'ALLOW_LOOSE'
timeout: '1200s'
tags: ['cubic-test-service-${_APP}-${_TF_ACTION}']
